###########################################################################
# This is an RMI mlwp-suite blueprint, which combines both the job        #
# script settings and the anemoi-graphs config into a single file.        #
# Settings for the job script are distinguished by lines starting with    #
# #@ .                                                                    #
###########################################################################

#### JOB SCRIPT SETTINGS ####

#@ time=00:10:00
#@ partition=dev-g
#@ container=anemoi-torch2.3.0-rocm6.0.3_20251006

#### ANEMOI-GRAPHS CONFIG ####

nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes
      dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
        norm: unit-max
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes
      resolution: 5
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
        norm: unit-max
edges:
- source_name: data
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 12
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
- source_name: hidden
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
    scale_resolutions: 5
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
- source_name: hidden
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 3
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
    