name: aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6

description: Dataset from 1979 to 2022, resolution n320. From ERA5 data, deterministic.
  See https://apps.ecmwf.int/mars-catalogue/?class=ea&stream=oper&expver=1&type=an&year=2023&month=jan&levtype=sfc

attribution: ECMWF

licence: CC-BY-4.0

dates:
  frequency: 6h
  start: '1979-01-01T00:00:00'
  end: '2022-12-31T18:00:00'

input:
  join:
  - mars:
      class: ea
      type: an
      stream: oper
      expver: '0001'
      grid: n320
      levtype: pl
      param:
      - q
      - t
      - u
      - v
      - w
      - z
      levelist:
      - 50
      - 100
      - 150
      - 200
      - 250
      - 300
      - 400
      - 500
      - 600
      - 700
      - 850
      - 925
      - 1000
  - mars:
      class: ea
      type: an
      stream: oper
      expver: '0001'
      grid: n320
      levtype: sfc
      param:
      - 10u
      - 10v
      - 2d
      - 2t
      - lsm
      - msl
      - sdor
      - skt
      - slor
      - sp
      - tcw
      - z
  - accumulations:
      class: ea
      type: an
      stream: oper
      expver: '0001'
      grid: n320
      levtype: sfc
      param:
      - cp
      - tp
      step: 6
  - forcings:
      template: ${input.join.0.mars}
      params:
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - insolation
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude

output:
  dtype: float32
  remapping:
    param_level: '{param}_{levelist}'

statistics: {}

build: {}

