overwrite: True
data: data 
hidden: hidden 

nodes:
  # Data nodes
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.ZarrDatasetNodes # options: ZarrDatasetNodes, NPZFileNodes
      dataset: ${dataloader.dataset}
    attributes: ${graph.attributes.nodes}
  # Hidden nodes
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes # options: ZarrDatasetNodes, NPZFileNodes, TriNodes
      resolution: 7 # grid resolution for npz (o32, o48, ...)
      reference_node_name: ${graph.data}
      mask_attr_name: cutout_mask

edges:
# Encoder configuration
- source_name: ${graph.data}
  target_name: ${graph.hidden}
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges # options: KNNEdges, CutOffEdges
    num_nearest_neighbours: 12 # only for knn method
  attributes: ${graph.attributes.edges}
  # Processor configuration
- source_name: ${graph.hidden}
  target_name: ${graph.hidden}
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
  attributes: ${graph.attributes.edges}
  # Decoder configuration
- source_name: ${graph.hidden}
  target_name: ${graph.data}
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges # options: KNNEdges, CutOffEdges
    target_mask_attr_name: cutout_mask
    num_nearest_neighbours: 3 # only for knn method
  attributes: ${graph.attributes.edges}

attributes:
  nodes:
    area_weight:
      _target_: anemoi.graphs.nodes.attributes.PlanarAreaWeights
    cutout_mask:
      _target_: anemoi.graphs.nodes.attributes.CutOutMask
    boundary_mask:
      _target_: anemoi.graphs.nodes.attributes.BooleanNot
      masks:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
  edges:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors:
- _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
  nodes_name: data
  ignore: cutout_mask # optional
  save_mask_indices_to_attr: indices_connected_nodes # optional