name: aifs-od-an-oper-0001-mars-n320-2016-2024-6h-v1-aifs-single-v1

description: Dataset from 2016 to 2024, resolution n320. Operational data, deterministic.
  See https://apps.ecmwf.int/mars-catalogue/?stream=oper&levtype=sfc&expver=1&month=jan&year=2024&type=an&class=od

input:
- sfc_data:
    kwargs:
      class: od
      date: $dates
      expver: '0001'
      grid: n320
      levtype: sfc
      name: mars
      param:
      - 10u
      - 10v
      - 2d
      - 2t
      - lsm
      - msl
      - sdor
      - skt
      - slor
      - sp
      - tcw
      - z
      - 100u
      - 100v
      - swvl1
      - swvl2
      - stl1
      - stl2
      - tcc
      - lcc
      - mcc
      - hcc
      stream: oper
      time:
      - 0
      - 6
      - 12
      - 18
      type: an
- acc_data:
    inherit: sfc_data
    kwargs:
      name: oper-accumulations
      param:
      - cp
      - tp
      - sf
      - ro
      - strd
      - ssrd
- pl_data:
    inherit: sfc_data
    kwargs:
      level:
      - 50
      - 100
      - 150
      - 200
      - 250
      - 300
      - 400
      - 500
      - 600
      - 700
      - 850
      - 925
      - 1000
      levtype: pl
      name: mars
      param:
      - q
      - t
      - u
      - v
      - w
      - z
- forcings:
    kwargs:
      name: constants
      param:
      - cos_latitude
      - cos_longitude
      - sin_latitude
      - sin_longitude
      - cos_julian_day
      - cos_local_time
      - sin_julian_day
      - sin_local_time
      - insolation
      source_or_dataset: $pl_data

output:
  chunking:
    valid_datetime: 1
  dtype: float32
  order_by:
  - valid_datetime
  - param_level:
    - q_50
    - q_100
    - q_150
    - q_200
    - q_250
    - q_300
    - q_400
    - q_500
    - q_600
    - q_700
    - q_850
    - q_925
    - q_1000
    - t_50
    - t_100
    - t_150
    - t_200
    - t_250
    - t_300
    - t_400
    - t_500
    - t_600
    - t_700
    - t_850
    - t_925
    - t_1000
    - u_50
    - u_100
    - u_150
    - u_200
    - u_250
    - u_300
    - u_400
    - u_500
    - u_600
    - u_700
    - u_850
    - u_925
    - u_1000
    - v_50
    - v_100
    - v_150
    - v_200
    - v_250
    - v_300
    - v_400
    - v_500
    - v_600
    - v_700
    - v_850
    - v_925
    - v_1000
    - w_50
    - w_100
    - w_150
    - w_200
    - w_250
    - w_300
    - w_400
    - w_500
    - w_600
    - w_700
    - w_850
    - w_925
    - w_1000
    - z_50
    - z_100
    - z_150
    - z_200
    - z_250
    - z_300
    - z_400
    - z_500
    - z_600
    - z_700
    - z_850
    - z_925
    - z_1000
    - 10u
    - 10v
    - 2d
    - 2t
    - lsm
    - msl
    - sdor
    - skt
    - slor
    - sp
    - tcw
    - z
    - 100u
    - 100v
    - swvl1
    - swvl2
    - stl1
    - stl2
    - tcc
    - lcc
    - mcc
    - hcc
    - cp
    - tp
    - sf
    - ro
    - strd
    - ssrd
    - cos_latitude
    - cos_longitude
    - sin_latitude
    - sin_longitude
    - cos_julian_day
    - cos_local_time
    - sin_julian_day
    - sin_local_time
    - insolation
  remapping:
    param_level: '{param}_{levelist}'
  statistics: param_level
  statistics_end: 2020

loop:
  dates:
    end: '2024-12-31'
    group_by: 10
    start: '2016-01-01'

