name: Create Discussion on PR Merge

on:
    pull_request:
        types: [closed]

jobs:
    create-discussion:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
          - name: Create Discussion
            uses: nvdaes/build-discussion@v1.0.29
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: ${{ github.event.pull_request.title }}
                body: |
                    ${{ github.event.pull_request.body }}
                category-position: 5